version: "3.8"
services:

    # PHP Service
    php:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        networks:
            - bridge

volumes:
    db-data: ~

networks:
  bridge: ~
